---
apiVersion: v1
kind: Service
metadata:
  name: competition-api-dev-local
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
      protocol: TCP
  selector:
    app: competition-api-dev-local
