FROM docker.io/golang:1.24-alpine AS builder

WORKDIR /app

COPY ./competition-api/go.mod ./competition-api/go.sum ./
RUN go mod download

# Copy in all of competition-api
COPY ./competition-api/ .

# -w    disable DWARF generation
# -s    disable symbol table
RUN go build -ldflags="-w -s" -o ./out/server ./cmd/server \
    && go build -ldflags="-w -s" -o ./out/worker ./cmd/worker \
    && go build -ldflags="-w -s" -o ./out/crs-status ./cmd/crs_status

FROM docker.io/alpine:3.21

WORKDIR /app
EXPOSE 1323

ARG USERNAME=competition-api
ARG USER_UID=1000

RUN addgroup -S docker
RUN adduser -S -u "${USER_UID}" -G docker ${USERNAME}

# Pin fuzzy versions https://superuser.com/a/1058665
# Update dind container if you bump this to ensure docker versions are the same
RUN apk add --no-cache \
    git~=2.47 \
    tar~=1.35 \
    bash~=5.2 \
    docker~=27.3 \
    python3~=3.12 \
    py3-yaml~=6.0 \
    git-lfs~=3.6

COPY ./competition-api/scripts/ /app/
COPY --from=builder /app/out/server /app/out/worker /app/out/crs-status /app/

USER ${USERNAME}

RUN git lfs install

ENTRYPOINT [ "/app/entrypoint.sh" ]
