FROM docker.io/golang:1.24-alpine AS builder

WORKDIR /app

# Fetch Dependencies sperately for faster rebuilds
COPY ./competition-api/go.mod ./competition-api/go.sum ./
RUN go mod download

# Copy in all of competition-api
COPY ./competition-api/ .

# -w    disable DWARF generation
# -s    disable symbol table
RUN go build -ldflags="-w -s" -o ./mock_jobrunner_bin ./cmd/mock_jobrunner

FROM alpine:3.21

WORKDIR /app

EXPOSE 1323

COPY --from=builder /app/mock_jobrunner_bin ./mock_jobrunner

CMD ["/app/mock_jobrunner"]
