FROM docker.io/golang:1.24-alpine AS builder

WORKDIR /app

# Fetch Dependencies sperately for faster rebuilds
COPY ./competition-api/go.mod ./competition-api/go.sum ./
RUN go mod download

# Copy in all of competition-api
COPY ./competition-api/ .

# -w    disable DWARF generation
# -s    disable symbol table
RUN go build -ldflags="-w -s" -o ./mock_crs_bin ./cmd/mock_crs

FROM alpine:3.21

WORKDIR /app

EXPOSE 1324

COPY --from=builder /app/mock_crs_bin ./mock_crs

CMD ["/app/mock_crs"]
