---
name: Images
on:
  push:
    branches:
      - main
    tags:
      - "*"

permissions:
  packages: write
  contents: read

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_TAG: ${{  github.ref_name }}

jobs:
  lowercase:
    runs-on: ubuntu-latest
    outputs:
      image_registry: ${{ steps.lowercase.outputs.image_registry }}
    steps:
      - name: Lowercase image registry name
        id: lowercase
        run: |
          echo "image_registry=${IMAGE_REGISTRY,,}" >> "$GITHUB_OUTPUT"

  compute-dir-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.compute-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compute Matrix
        id: compute-matrix
        run: |
          dirs=$(make container-dirs | xargs -n 1 | jq -R . | jq -cs .)
          echo "matrix=${dirs}" >> "$GITHUB_OUTPUT"

  compute-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.tags.outputs.tags }}
    steps:
      - name: Build image tags list
        id: tags
        run: |
          if [[ "${{ env.IMAGE_TAG }}" == "main" ]]; then
              echo 'tags=latest main-'"$(date -u +%Y%m%dT%H%M%SZ)" >> "$GITHUB_OUTPUT"
          else
              echo 'tags=${{ env.IMAGE_TAG }}' >> "$GITHUB_OUTPUT"
          fi

  compute-changed-files:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.processed.outputs.changed-files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Changed Files
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            repo:
              - '**'
          list-files: "json"
      - name: Process
        id: processed
        run: |
          processed=$(echo '${{ steps.changes.outputs.repo_files }}' | jq -r '.[]' | xargs realpath | jq -R | jq -cs .)
          echo "changed-files=${processed}" > "$GITHUB_OUTPUT"
  images:
    needs:
      - compute-dir-matrix
      - compute-tags
      - compute-changed-files
      - lowercase
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJSON(needs.compute-dir-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: should-build
        id: should-build
        run: |
          if make should-build CONTAINER_DIRS='${{ matrix.dir }}' CHANGED_FILES='${{ needs.compute-changed-files.outputs.changed-files }}'; then should_build=1; else should_build=0; fi
          echo "should-build=${should_build}" > "$GITHUB_OUTPUT"

      - name: Remove extras
        if: ${{ (steps.should-build.outputs.should-build == '1') || startsWith(github.ref, 'refs/tags') }}
        run: |
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Log in to ghcr.io
        if: ${{ (steps.should-build.outputs.should-build == '1') || startsWith(github.ref, 'refs/tags') }}
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ needs.lowercase.outputs.image_registry }}

      - name: podman build
        if: ${{ (steps.should-build.outputs.should-build == '1') || startsWith(github.ref, 'refs/tags') }}
        run: make podman-build CONTAINER_DIRS='${{ matrix.dir }}' IMAGE_TAGS='${{ needs.compute-tags.outputs.tags }}' IMAGE_LABELS='org.opencontainers.image.revision=${{ github.sha }}'

      - name: podman push
        if: ${{ (steps.should-build.outputs.should-build == '1') || startsWith(github.ref, 'refs/tags') }}
        run: make podman-push CONTAINER_DIRS='${{ matrix.dir }}' IMAGE_TAGS='${{ needs.compute-tags.outputs.tags }}'
