name: Upload Go test results

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: competition-api/go.sum
      - name: Install dependencies
        run: |
          cd competition-api
          go mod download
      - name: Test with Go
        run: |
          cd competition-api
          go test -json -cover ./... | tee TestResults-${{ matrix.go-version }}.json && exit "${PIPESTATUS[0]}"
      - name: Upload Go test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: ./competition-api/TestResults-${{ matrix.go-version }}.json
